# coding: utf-8

"""
    Hydra OAuth2 & OpenID Connect Server

    Please refer to the user guide for in-depth documentation: https://ory.gitbooks.io/hydra/content/   Hydra offers OAuth 2.0 and OpenID Connect Core 1.0 capabilities as a service. Hydra is different, because it works with any existing authentication infrastructure, not just LDAP or SAML. By implementing a consent app (works with any programming language) you build a bridge between Hydra and your authentication infrastructure. Hydra is able to securely manage JSON Web Keys, and has a sophisticated policy-based access control you can use if you want to. Hydra is suitable for green- (new) and brownfield (existing) projects. If you are not familiar with OAuth 2.0 and are working on a greenfield project, we recommend evaluating if OAuth 2.0 really serves your purpose. Knowledge of OAuth 2.0 is imperative in understanding what Hydra does and how it works.   The official repository is located at https://github.com/ory/hydra   ### Important REST API Documentation Notes  The swagger generator used to create this documentation does currently not support example responses. To see request and response payloads click on **\"Show JSON schema\"**: ![Enable JSON Schema on Apiary](https://storage.googleapis.com/ory.am/hydra/json-schema.png)   The API documentation always refers to the latest tagged version of ORY Hydra. For previous API documentations, please refer to https://github.com/ory/hydra/blob/<tag-id>/docs/api.swagger.yaml - for example:  0.9.13: https://github.com/ory/hydra/blob/v0.9.13/docs/api.swagger.yaml 0.8.1: https://github.com/ory/hydra/blob/v0.8.1/docs/api.swagger.yaml

    OpenAPI spec version: Latest
    Contact: hi@ory.am
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .consent_request import ConsentRequest
from .consent_request_acceptance import ConsentRequestAcceptance
from .consent_request_manager import ConsentRequestManager
from .consent_request_rejection import ConsentRequestRejection
from .context import Context
from .firewall import Firewall
from .group import Group
from .group_members import GroupMembers
from .handler import Handler
from .inline_response_200 import InlineResponse200
from .inline_response_200_1 import InlineResponse2001
from .inline_response_401 import InlineResponse401
from .jose_web_key_set_request import JoseWebKeySetRequest
from .json_web_key import JsonWebKey
from .json_web_key_set import JsonWebKeySet
from .json_web_key_set_generator_request import JsonWebKeySetGeneratorRequest
from .key_generator import KeyGenerator
from .manager import Manager
from .o_auth2_client import OAuth2Client
from .o_auth2_consent_request import OAuth2ConsentRequest
from .o_auth2_token_introspection import OAuth2TokenIntrospection
from .policy import Policy
from .policy_conditions import PolicyConditions
from .raw_message import RawMessage
from .swagger_accept_consent_request import SwaggerAcceptConsentRequest
from .swagger_create_policy_parameters import SwaggerCreatePolicyParameters
from .swagger_does_warden_allow_access_request_parameters import SwaggerDoesWardenAllowAccessRequestParameters
from .swagger_does_warden_allow_token_access_request_parameters import SwaggerDoesWardenAllowTokenAccessRequestParameters
from .swagger_get_policy_parameters import SwaggerGetPolicyParameters
from .swagger_json_web_key_query import SwaggerJsonWebKeyQuery
from .swagger_jwk_create_set import SwaggerJwkCreateSet
from .swagger_jwk_set_query import SwaggerJwkSetQuery
from .swagger_jwk_update_set import SwaggerJwkUpdateSet
from .swagger_jwk_update_set_key import SwaggerJwkUpdateSetKey
from .swagger_list_policy_parameters import SwaggerListPolicyParameters
from .swagger_list_policy_response import SwaggerListPolicyResponse
from .swagger_o_auth_consent_request import SwaggerOAuthConsentRequest
from .swagger_o_auth_consent_request_payload import SwaggerOAuthConsentRequestPayload
from .swagger_o_auth_introspection_request import SwaggerOAuthIntrospectionRequest
from .swagger_o_auth_introspection_response import SwaggerOAuthIntrospectionResponse
from .swagger_o_auth_token_response import SwaggerOAuthTokenResponse
from .swagger_o_auth_token_response_body import SwaggerOAuthTokenResponseBody
from .swagger_reject_consent_request import SwaggerRejectConsentRequest
from .swagger_revoke_o_auth2_token_parameters import SwaggerRevokeOAuth2TokenParameters
from .swagger_update_policy_parameters import SwaggerUpdatePolicyParameters
from .swagger_warden_access_request_response_parameters import SwaggerWardenAccessRequestResponseParameters
from .swagger_warden_token_access_request_response import SwaggerWardenTokenAccessRequestResponse
from .token_allowed_request import TokenAllowedRequest
from .warden_access_request import WardenAccessRequest
from .warden_access_request_response import WardenAccessRequestResponse
from .warden_token_access_request import WardenTokenAccessRequest
from .warden_token_access_request_response import WardenTokenAccessRequestResponse
from .well_known import WellKnown
from .writer import Writer
